import "~/styles/globals.css";
import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { ThemeProvider } from "~/app/_components/theme-provider";

import SideBar from "~/app/_components/user-componects/sideBar";

export const metadata = {
  title: "Fire Bird",
  description: "A Mailing service Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function UserLayout({
  children,
  content
}: {
  children: React.ReactNode;
  content: React.ReactNode
}) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <TRPCReactProvider>
        <SpeedInsights />
        <main className="flex flex-row bg-inactive">
          <SideBar />
          <div className="flex h-screen w-full flex-row">
        {children}
            
            <div className="flex grow flex-col">
              <div className="h-20">nav</div>
              <div className="bg-inactive grow rounded-tl-3xl">
                <div className="bg-inactive h-full w-full rounded-tl-2xl border-l-4 border-t-4 border-black dark:border-white">
                  {content}
                </div>
              </div>
            </div>
          </div>
        </main>
      </TRPCReactProvider>
    </ThemeProvider>
  );
}
